### ISSUE TITLE
Resume appears but haven't played presentation

### ISSUE THREAD

**Issue by patrick-wirth** [uwex-learning-tech/audioplayer#8]
Hi Ethan,

I'm working on transcripts for APC 470.  The Resume button appears on the splash screen but I haven't interacted with the presentation previously.  This is happening on a regular basis. 

Here's the course I'm working on: https://media.uwex.edu/content/apc/apc470/apc470_project_overview/index.html

Patrick

**Comment by Lin87** [comment]
So sorry. This "will fix shortyly" turned out to be almost 2 years. It is now resuming for the right track and presentation. Fixed in commit 22751c8.
